version: '3.9'
name: m183_todo
services:
  mysql:
    build: ./docker/mysql
    container_name: m183-mysql
    restart: always
    env_file:
      - ./docker/mysql/.env
    ports:
      - "3306:3306"
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: m183-php
    restart: always
    env_file:
      - ./docker/php/.env
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
