version: '3.9'
name: m183_todo-dev
services:
  mysql:
    build: ./docker/mysql
    container_name: m183-mysql
    restart: always
    env_file:
      - ./docker/mysql/.env
    ports:
      - "3306:3306"
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.dev
    container_name: m183-php
    restart: always
    env_file:
      - ./docker/php/.env
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
      - type: bind
        source: ./docker/php/conf.d/xdebug.ini
        target: /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - type: bind
        source: ./docker/php/conf.d/error_reporting.ini
        target: /usr/local/etc/php/conf.d/error_reporting.ini
      - type: bind
        source: ./docker/php/.htaccess
        target: /var/www/html/.htaccess
